import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Link from 'next/link';
import StoreFront from '../images/storeFront.png';
import mapImage from '../images/staticmap.png';
import Script from 'next/script';

export default function About() {
    return(
        <div>
            <Head>
                <title>Georgetown Cafe - About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <html data-theme="light"></html>
            </Head>

            <Script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></Script>

            <Navbar />
            <main className="w-full h-full mb-10">
                <div className="container max-w-[1440px] mx-auto">
                    <div className="px-5 align-center text-center">
                        <div className="text-md breadcrumbs my-3">
                            <ul>
                                <Link href="/">
                                    <li><a>Home</a></li>  
                                </Link>
                                    <li>About</li> 
                            </ul>
                        </div>
                        <div className="about flex flex-col lg:flex-row w-9/12 justify-between">
                            <div>
                                <Image alt="store" draggable="false" src={StoreFront} width={400} height={600} />
                            </div>
                            <div>
                                <h1 className="text-4xl font-bold">Where can you find us?</h1>
                                <br />
                                <div className="space-y-2">
                                    <div>
                                        <p className="text-lg">Our new location is located at <a className="underline text-blue-500" target="blank" href="https://www.google.com/maps/place/Georgetown+cafe+1/@38.060574,-84.5039751,17z/data=!3m1!4b1!4m5!3m4!1s0x8842447b4b7a0b77:0x170532cb3ac0b27a!8m2!3d38.0605656!4d-84.5018241">417 Georgetown st Lexington, KY 40508</a></p>
                                    </div>
                                    <div>
                                        <a target="blank" href="https://www.google.com/maps/place/Georgetown+cafe+1/@38.060574,-84.5039751,17z/data=!3m1!4b1!4m5!3m4!1s0x8842447b4b7a0b77:0x170532cb3ac0b27a!8m2!3d38.0605656!4d-84.5018241">
                                        <Image alt="" draggable="false" src={mapImage} width={300} height={150} />
                                        </a>
                                    </div>
                                </div>
                                <br />
                                <div className="faq space-y-2">
                                    <h1 className="text-4xl font-bold">Here are some FAQ's</h1>
                                    <br />
                                    <div tabIndex="0" className="collapse border border-base-300 bg-base-100 rounded-box collapse-arrow">
                                        <div className="collapse-title text-xl font-medium">
                                            "Do you deliver?"
                                        </div>
                                        <div tabIndex="0" className="collapse-content"> 
                                            <p>We do not deliver but we do offer curbside pick up!</p>
                                        </div>
                                    </div>
                                    <div tabIndex="0" className="collapse border border-base-300 bg-base-100 rounded-box collapse-arrow">
                                        <div className="collapse-title text-xl font-medium">
                                        "When are you open?"
                                        </div>
                                        <div className="collapse-content"> 
                                            <p>Were open Monday - Saturday from 11:00AM to 6:00PM</p>
                                        </div>
                                    </div>
                                    <div tabIndex="0" className="collapse border border-base-300 bg-base-100 rounded-box collapse-arrow">
                                        <div className="collapse-title text-xl font-medium">
                                            "Do you take call in orders?"
                                        </div>
                                        <div className="collapse-content"> 
                                            <p>Yes we do! you can call us at (859)-309-2777</p>
                                        </div>
                                    </div>
                                    <div tabIndex="0" className="collapse border border-base-300 bg-base-100 rounded-box collapse-arrow">
                                        <div className="collapse-title text-xl font-medium">
                                            "How is Georgetown Cafe rated?"
                                        </div>
                                        <div className="collapse-content"> 
                                            <p>Georgetown Cafe has an average rating of 4.7!</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    )
}