import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Link from 'next/link';
import gtcBanner from '../images/gtcbanner.png';
import { StarIcon } from '@heroicons/react/solid';
import Menu1 from '../images/menu.jpg';
import Menu2 from '../images/menu2.jpg';
import Script from 'next/script';

export default function Menu() {
    return(
        <div>
            <Head>
                <title>Georgetown Cafe - Menu</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <html data-theme="light"></html>
            </Head>

            <Script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></Script>

            <Navbar />
            <main className="w-screen h-full">
                <div className="container max-w-[1440px] mx-auto">
                    <div className="banner mt-3 relative">
                        <Image alt="" draggable="false" className="z-0" src={gtcBanner} width={1440} height={450} />
                        <div className="absolute z-10 bottom-0 p-5  md:p-10 align-center items-center">
                            <h1 className="text-white text-4xl">Georgetown Cafe</h1>
                                <ul className="flex space-x-2 mt-2 bg-red-400 w-fit rounded-md">
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                </ul>
                            <div className="text-white mt-1">
                                <span className="">Rating 4.7</span>   
                            </div>
                        </div>
                    </div>
                    <div className="text-md breadcrumbs my-3 px-5">
                        <ul>
                            <Link href="/">
                                <li><a>Home</a></li>  
                            </Link>
                            <li>Menu</li> 
                        </ul>
                    </div>
                    <div className="menu-content mt-20 px-10 items-center">
                        <table className="mb-2">
                            <tr>
                                <th>
                                    <h1 className="border-b-2 md:border-none text-left text-xl md:text-2xl text-gray-600">Sub, Pita and Sandwich (All served with 1 side)</h1>
                                    <div className="hidden md:inline-block border-b-2 w-[1440px] my-2"></div>
                                </th>
                            </tr>
                            <tr>
                                <td className="text-lg font-bold text-center">
                                    <div className="flex flex-col lg:grid lg:grid-cols-2">
                                        <div className="flex flex-col w-96">
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Philly Cheese Steak</span>
                                                <span>$8.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Chicken Philly</span>
                                                <span>$8.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Bourbon Chicken Sub</span>
                                                <span>$8.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Teriyaki Chicken Sub</span>
                                                <span>$8.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Buffalo Chicken Sub</span>
                                                <span>$8.99</span>
                                            </div>
                                        </div>
                                        <div className="flex flex-col w-96">
                                        <div className="flex justify-between border-b-2 mb-2">
                                                <span>Cajun Chicken Sub</span>
                                                <span>$8.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>1/2 lb. Cheese Burger</span>
                                                <span>$8.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Lamb Gyro</span>
                                                <span>$8.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span><p>All Phillys and Subs come with (Banana Peppers, Grilled Onions, Lettuce, Tomato, Mayo and Provolone Cheese.)</p></span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <table className="mb-2">
                            <tr>
                                <th>
                                    <h1 className="border-b-2 md:border-none text-left text-xl md:text-2xl text-gray-600">Entrees</h1>
                                    <div className="hidden md:inline-block border-b-2 w-[1440px] my-2"></div>
                                </th>
                            </tr>
                            <tr>
                                <td className="text-lg font-bold text-center">
                                    <div className="flex flex-col lg:grid lg:grid-cols-2">
                                        <div className="flex flex-col w-96">
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Edible Bowl</span>
                                                <span>$9.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Burrito</span>
                                                <span>$9.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Loaded Baked Potato</span>
                                                <span>$9.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Salad</span>
                                                <span>$8.99</span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <table className="mb-2">
                            <tr>
                                <th>
                                    <h1 className="border-b-2 md:border-none text-left text-xl md:text-2xl text-gray-600">Side Orders</h1>
                                    <div className="hidden md:inline-block border-b-2 w-[1440px] my-2"></div>
                                </th>
                            </tr>
                            <tr>
                                <td className="text-lg font-bold text-center">
                                    <div className="flex flex-col lg:grid lg:grid-cols-2">
                                        <div className="flex flex-col w-96">
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Spicy, Veggie, White Rice</span>
                                                <span>$2.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Cajun Potatoes</span>
                                                <span>$2.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Fries</span>
                                                <span>$2.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Steamed Veggies</span>
                                                <span>$2.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Green Beans</span>
                                                <span>$2.99</span>
                                            </div>
                                        </div>
                                        <div className="flex flex-col w-96">
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Sweet Corn</span>
                                                <span>$2.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Add cheese and sour cream</span>
                                                <span>$2.00</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Desserts</span>
                                                <span>$2.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Drinks</span>
                                                <span>$1.00</span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <table className="mb-2">
                            <tr>
                                <th>
                                    <h1 className="border-b-2 md:border-none text-left text-xl md:text-2xl text-gray-600">Appetizers</h1>
                                    <div className="hidden md:inline-block border-b-2 w-[1440px] my-2"></div>
                                </th>
                            </tr>
                            <tr>
                                <td className="text-lg font-bold text-center">
                                    <div className="flex flex-col lg:grid lg:grid-cols-2">
                                        <div className="flex flex-col w-96">
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Veggie Egg Rolls</span>
                                                <span>$4.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Samosa</span>
                                                <span>$4.99</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Salad</span>
                                                <span>$3.99</span>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <table className="mb-2">
                            <tr>
                                <th>
                                    <h1 className="border-b-2 md:border-none text-left text-xl md:text-2xl text-gray-600">Dinners (Small , Large)</h1>
                                    <div className="hidden md:inline-block border-b-2 w-[1440px] my-2"></div>
                                </th>
                            </tr>
                            <tr>
                                <td className="text-lg font-bold text-center">
                                    <div className="flex flex-col lg:grid lg:grid-cols-2">
                                        <div className="flex flex-col w-96">
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Bourbon Chicken</span>
                                                <span>$6.99 s , $9.99 L</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Cajun Chicken</span>
                                                <span>$6.99 s , $9.99 L</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Seasoned Chicken</span>
                                                <span>$6.99 s , $9.99 L</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Curry Chicken</span>
                                                <span>$6.99 s , $9.99 L</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Teriyaki Chicken</span>
                                                <span>$6.99 s , $9.99 L</span>
                                            </div>
                                        </div>
                                    <div className="flex flex-col lg:grid lg:grid-cols-2">
                                        <div className="flex flex-col w-96">
                                            <div className="flex justify-between border-b-2 mb-2">
                                                <span>Buffalo Chicken</span>
                                                <span>$6.99 s , $9.99 L</span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                            <span><p>All Large Dinners are served with 2 sides.</p></span>
                                            </div>
                                            <div className="flex justify-between border-b-2 mb-2">
                                            <span><p>All Small Dinners are served with 1 side.</p></span>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div className="flex flex-col lg:flex-row justify-between w-full my-5 px-10">
                        <div>
                            <a target="blank" href="https://www.facebook.com/Georgetown-Cafe-1-1909672329271844/photos/2994230914149308">
                                <Image alt="" className="rounded-xl" src={Menu1} width={500} height={300} />
                            </a>
                        </div>
                        <div>
                            <a target="blank" href="https://www.facebook.com/Georgetown-Cafe-1-1909672329271844/photos/2994230907482642">
                                <Image alt="" className="rounded-xl" src={Menu2} width={500} height={300} />
                            </a>
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    )
}