import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Link from 'next/link';
import gtcBanner from '../images/gtcbanner.png';
import { StarIcon } from '@heroicons/react/solid';
import Menu1 from '../images/menu.jpg';
import Menu2 from '../images/menu2.jpg';
import Script from 'next/script';

export default function Menu() {
    return(
        <div>
            <Head>
                <title>Georgetown Cafe - Reviews</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <html data-theme="light"></html>
            </Head>

            <Script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></Script>
            
            <Navbar />
            <main className="w-screen h-full">
                <div className="container max-w-[1440px] mx-auto">
                    <div className="banner mt-3 relative">
                        <Image draggable="false" className="z-0" src={gtcBanner} width={1440} height={450} />
                        <div className="absolute z-10 bottom-0 p-5 md:p-10 align-center items-center">
                            <h1 className="text-white text-4xl">Georgetown Cafe</h1>
                                <ul className="flex space-x-2 mt-2 bg-red-400 w-fit rounded-md">
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                    <li>
                                        <StarIcon className="w-8 text-white" />
                                    </li>
                                </ul>
                            <div className="text-white mt-1">
                                <span className="">Rating 4.7</span>   
                            </div>
                        </div>
                    </div>
                    <div className="text-md breadcrumbs my-3 px-5">
                        <ul>
                            <Link href="/">
                                <li><a>Home</a></li>  
                            </Link>
                            <li>Reviews</li> 
                        </ul>
                    </div>
                    <div className="reviews mb-10">
                        <div className="w-full text-center mb-28 text-4xl font-bold mt-8">
                            <h1>Haven't decided if you should order? well here are some reviews!</h1>
                        </div>
                        <div className="flex flex-col lg:grid lg:grid-cols-3 space-x-4 space-y-4 items-center">
                            <div className="card w-96 bg-base-100 shadow-xl">
                                <figure className="px-10 pt-10">
                                <box-icon size="md" type='logo' name='facebook-circle'></box-icon>
                                </figure>
                                <div className="card-body items-center text-center">
                                    <h2 className="card-title">Review from Facebook</h2>
                                    <p>Fast friendly service,  delicious food at a great price and generous portions. 😋
                                    Cheap eats.</p>
                                </div>
                            </div>
                            <div className="card w-96 bg-base-100 shadow-xl">
                                <figure className="px-10 pt-10">
                                <box-icon size="md" type='logo' name='facebook-circle'></box-icon>
                                </figure>
                                <div className="card-body items-center text-center">
                                    <h2 className="card-title">Review from Facebook</h2>
                                    <p>I've been twice now since the reopen. Everything has been bomb. My wife goes in and does the ordering and she says the staff is friendly as can be. Plus the portions are insanely huge for the price. Hellz yes I'll be back.</p>
                                </div>
                            </div>
                            <div className="card w-96 bg-base-100 shadow-xl">
                                <figure className="px-10 pt-10">
                                <box-icon size="md" type='logo' name='facebook-circle'></box-icon>
                                </figure>
                                <div className="card-body items-center text-center">
                                    <h2 className="card-title">Review from Facebook</h2>
                                    <p>Their back! Super delicious.</p>
                                </div>
                            </div>
                            <div className="card w-96 bg-base-100 shadow-xl">
                                <figure className="px-10 pt-10">
                                <box-icon size="md" type='logo' name='facebook-circle'></box-icon>
                                </figure>
                                <div className="card-body items-center text-center">
                                    <h2 className="card-title">Review from Facebook</h2>
                                    <p>The Bourbon Chicken is soo sooo good.</p>
                                </div>
                            </div>
                            <div className="card w-96 bg-base-100 shadow-xl">
                                <figure className="px-10 pt-10">
                                <box-icon size="md" type='logo' name='facebook-circle'></box-icon>
                                </figure>
                                <div className="card-body items-center text-center">
                                    <h2 className="card-title">Review from Facebook</h2>
                                    <p>The bourbon chicken is heaven in a box!  This place really lives up to the hype and you've got a new regular.</p>
                                </div>
                            </div>
                            <div className="card w-96 bg-base-100 shadow-xl">
                                <figure className="px-10 pt-10">
                                <box-icon size="md" type='logo' name='facebook-circle'></box-icon>
                                </figure>
                                <div className="card-body items-center text-center">
                                    <h2 className="card-title">Review from Facebook</h2>
                                    <p>The most awesome Bourbon Chicken and Spicy Rice in Lex!.</p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </main>
            <Footer />
        </div>
    )
}